name = "my-mastra-app"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "mastra-db"
database_id = "4d05f774-1585-4c95-ae2b-56aad4811596"

[build]
command = "npm run build" 